#!/usr/bin/bash

source .env

user_pool_file="./user_pool"
count=0
if test ! -e ./user_pool
then 
  touch ./user_pool
  echo "$USERNAME$count" >> $user_pool_file
fi


username=${USERNAME}
while grep "${USERNAME}${count}" $user_pool_file
do 
  count=`expr $count + 1`
  username="${USERNAME}${count}"
done
echo "$username" >> $user_pool_file
user_pass="test2"

sudo -S useradd $username
sudo -S sed -i -e "s/\/bin\/sh/\/usr\/bin\/bash/" /etc/passwd
sudo -S mkdir "/home/$username"
sudo -S chown -R $username:$username "/home/$username/"
sudo -S chmod -R 750 "/home/$username"
echo "$username:$user_pass" | sudo chpasswd
sudo -u $username -i

tail -f /dev/null
